//! Build-time code generation of the K8s protobuf schema registry.
//!
//! We compile the vendored upstream `k8s.io/api` + `apimachinery` `.proto`
//! files into a self-contained FileDescriptorSet with `protoc`, then walk it
//! and emit the field-number -> (jsonName, FieldType) table the runtime
//! decoder uses. This makes field numbers impossible to transcribe wrong (the
//! whole "hand-maintained registry drifts" bug class) — protoc is the source
//! of truth.
//!
//! A small, curated OVERRIDES layer encodes the handful of things that are NOT
//! expressible in the proto (K8s custom JSON marshaling / Go `,inline` embeds):
//!   * intstr.IntOrString      -> FieldType::IntOrString
//!   * runtime.RawExtension    -> FieldType::JsonRaw
//!   * api.resource.Quantity   -> String (K8s marshals Quantity as a bare string)
//!   * fields named volumeSource / persistentVolumeSource / localObjectReference
//!     are Go `,inline` embeds -> FieldType::Inlined(<type>)
//!
//! The generated table is applied as an OVERLAY on top of the hand-written base
//! registry in lib.rs (generated wins), so vendoring more groups later strictly
//! shrinks the hand-maintained surface without risking regressions.

use prost::Message;
use prost_types::{
    field_descriptor_proto::{Label, Type},
    DescriptorProto, FieldDescriptorProto, FileDescriptorSet,
};
use std::collections::HashMap;
use std::path::PathBuf;

fn main() {
    let proto_root = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("proto");
    println!("cargo:rerun-if-changed={}", proto_root.display());

    // Collect all vendored .proto files.
    let mut protos = Vec::new();
    collect_protos(&proto_root, &mut protos);
    protos.sort();

    let out_dir = PathBuf::from(env("OUT_DIR"));
    let fds_path = out_dir.join("k8s.fds");

    // Compile to a FileDescriptorSet via protoc.
    let protoc = std::env::var("PROTOC").unwrap_or_else(|_| "protoc".to_string());
    let mut cmd = std::process::Command::new(&protoc);
    cmd.arg("--include_imports")
        .arg("-o")
        .arg(&fds_path)
        .arg("-I")
        .arg(&proto_root);
    // google/protobuf well-known types (descriptor.proto), needed by gogo.proto.
    if let Ok(inc) = std::env::var("PROTOC_INCLUDE") {
        cmd.arg("-I").arg(inc);
    }
    for p in &protos {
        cmd.arg(p);
    }
    let status = cmd.status().unwrap_or_else(|e| {
        panic!("failed to run protoc ({protoc}): {e}. Set PROTOC to its path.")
    });
    assert!(status.success(), "protoc failed compiling k8s protos");

    let bytes = std::fs::read(&fds_path).expect("read FDS");
    let fds = FileDescriptorSet::decode(bytes.as_slice()).expect("decode FDS");

    // Index every message by fully-qualified name (incl. nested), so we can
    // resolve field type_names and detect map-entry synthetic messages.
    let mut by_fqn: HashMap<String, &DescriptorProto> = HashMap::new();
    for file in &fds.file {
        let pkg = file.package();
        for msg in &file.message_type {
            index_message(pkg, msg, &mut by_fqn);
        }
    }

    // Emit one MessageSchema per top-level message in a k8s.io.* package,
    // keyed by short name. Error on a genuine short-name collision.
    let mut out = String::new();
    out.push_str("// @generated by build.rs from vendored k8s.io/api protos. Do not edit.\n");
    out.push_str("pub(crate) fn generated_schemas(schemas: &mut std::collections::HashMap<String, MessageSchema>) {\n");

    let mut emitted: HashMap<String, (String, &DescriptorProto)> = HashMap::new(); // short -> (fqn, msg)
    for file in &fds.file {
        let pkg = file.package();
        if !pkg.starts_with("k8s.io") {
            continue; // skip google.protobuf / gogoproto
        }
        // runtime/* types (TypeMeta, RawExtension, Unknown) are only needed as
        // protoc imports; RawExtension is handled via a field-type override and
        // the Unknown envelope is parsed separately. Skipping them also avoids a
        // TypeMeta short-name collision with meta/v1.
        if pkg == "k8s.io.apimachinery.pkg.runtime"
            || pkg == "k8s.io.apimachinery.pkg.runtime.schema"
        {
            continue;
        }
        for msg in &file.message_type {
            let short = msg.name().to_string();
            if msg
                .options
                .as_ref()
                .map(|o| o.map_entry())
                .unwrap_or(false)
            {
                continue;
            }
            let fqn = format!(".{pkg}.{short}");
            const META_V1: &str = "k8s.io.apimachinery.pkg.apis.meta.v1";
            if let Some((prev_fqn, prev_msg)) = emitted.get(&short).cloned() {
                if prev_fqn == fqn {
                    continue;
                }
                // Same short name in two packages. Tolerate when structurally
                // identical (decoding either way yields the same JSON).
                if field_shape(prev_msg) == field_shape(msg) {
                    continue;
                }
                // They differ. Generic types (Preconditions, ...) exist in both
                // apimachinery meta/v1 and core/v1 with different shapes; the
                // meta/v1 definition is the canonical one referenced by generic
                // options types, so it wins. Anything else is an unexpected
                // cross-group clash that must be curated.
                if pkg == META_V1 {
                    println!("cargo:warning=k8s-proto: `{short}` in {prev_fqn} overridden by {fqn} (meta/v1 canonical)");
                    emitted.insert(short.clone(), (fqn.clone(), msg));
                    emit_message(&mut out, &short, msg, &by_fqn);
                } else {
                    // Unforeseen cross-group same-name clash (e.g. core.EndpointPort
                    // vs discovery.EndpointPort). Keep the first-seen definition and
                    // warn rather than fail the build; adding a proto group must
                    // never break compilation. Curate the vendored set if the wrong
                    // one wins for a type that is actually decoded.
                    println!("cargo:warning=k8s-proto: `{short}` clash — kept {prev_fqn}, skipped {fqn}");
                }
                continue;
            }
            emitted.insert(short.clone(), (fqn.clone(), msg));
            emit_message(&mut out, &short, msg, &by_fqn);
        }
    }
    out.push_str("}\n");

    std::fs::write(out_dir.join("generated_registry.rs"), out).expect("write generated");
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("{k} not set"))
}

/// A comparable shape of a message's fields (number, jsonName, type, type_name),
/// used to decide whether two same-short-named messages are interchangeable.
fn field_shape(msg: &DescriptorProto) -> Vec<(i32, String, i32, String)> {
    let mut v: Vec<_> = msg
        .field
        .iter()
        .map(|f| {
            (
                f.number(),
                f.json_name().to_string(),
                f.r#type() as i32,
                f.type_name().to_string(),
            )
        })
        .collect();
    v.sort();
    v
}

fn collect_protos(dir: &std::path::Path, out: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect_protos(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("proto") {
            // Skip gogoproto — options only, not a resource package.
            if !path.to_string_lossy().contains("gogo/protobuf") {
                out.push(path);
            }
        }
    }
}

fn index_message<'a>(
    prefix: &str,
    msg: &'a DescriptorProto,
    by_fqn: &mut HashMap<String, &'a DescriptorProto>,
) {
    let fqn = format!(".{prefix}.{}", msg.name());
    by_fqn.insert(fqn.clone(), msg);
    let inner_prefix = format!("{prefix}.{}", msg.name());
    for nested in &msg.nested_type {
        index_message(&inner_prefix, nested, by_fqn);
    }
}

fn emit_message(
    out: &mut String,
    short: &str,
    msg: &DescriptorProto,
    by_fqn: &HashMap<String, &DescriptorProto>,
) {
    if msg.field.is_empty() {
        // Empty HashMap::from([]) can't infer its element type.
        out.push_str(&format!(
            "    schemas.insert({short:?}.to_string(), MessageSchema {{ fields: std::collections::HashMap::new() }});\n"
        ));
        return;
    }
    out.push_str(&format!(
        "    schemas.insert({short:?}.to_string(), MessageSchema {{ fields: std::collections::HashMap::from([\n"
    ));
    for field in &msg.field {
        let number = field.number();
        let json = field.json_name();
        let ft = field_type_expr(field, by_fqn);
        out.push_str(&format!(
            "        ({number}u32, ({json:?}.to_string(), {ft})),\n"
        ));
    }
    out.push_str("    ]) });\n");
}

/// Short name = last dotted segment of a `.pkg.Msg` type_name.
fn short_of(type_name: &str) -> &str {
    type_name.rsplit('.').next().unwrap_or(type_name)
}

/// Render a `FieldType` constructor expression for one field.
fn field_type_expr(field: &FieldDescriptorProto, by_fqn: &HashMap<String, &DescriptorProto>) -> String {
    let json = field.json_name();

    // map<K,V> is a repeated synthetic entry message.
    if field.label() == Label::Repeated && field.r#type() == Type::Message {
        if let Some(entry) = by_fqn.get(field.type_name()) {
            if entry.options.as_ref().map(|o| o.map_entry()).unwrap_or(false) {
                let value = entry.field.iter().find(|f| f.number() == 2);
                return match value {
                    Some(v) if v.r#type() == Type::Message => {
                        // map<string, Quantity> is stored as string values by K8s
                        // JSON; other message maps decode each value.
                        if short_of(v.type_name()) == "Quantity" {
                            "FieldType::StringMap".to_string()
                        } else {
                            format!("FieldType::MessageMap({:?}.to_string())", short_of(v.type_name()))
                        }
                    }
                    _ => "FieldType::StringMap".to_string(),
                };
            }
        }
    }

    // Repeated non-map: Repeated(inner).
    if field.label() == Label::Repeated {
        let inner = scalar_or_message_expr(field, by_fqn, json);
        return format!("FieldType::Repeated(Box::new({inner}))");
    }

    scalar_or_message_expr(field, by_fqn, json)
}

fn scalar_or_message_expr(
    field: &FieldDescriptorProto,
    _by_fqn: &HashMap<String, &DescriptorProto>,
    json: &str,
) -> String {
    match field.r#type() {
        Type::String => "FieldType::String".to_string(),
        Type::Bool => "FieldType::Bool".to_string(),
        Type::Bytes => "FieldType::Bytes".to_string(),
        Type::Int32 | Type::Int64 | Type::Uint32 | Type::Uint64 | Type::Sint32
        | Type::Sint64 | Type::Fixed32 | Type::Fixed64 | Type::Sfixed32
        | Type::Sfixed64 | Type::Enum | Type::Double | Type::Float => "FieldType::Int".to_string(),
        Type::Message | Type::Group => {
            let tn = field.type_name();
            let short = short_of(tn);
            // Curated K8s custom-marshaling / inline overrides.
            match tn {
                ".k8s.io.apimachinery.pkg.util.intstr.IntOrString" => {
                    return "FieldType::IntOrString".to_string()
                }
                ".k8s.io.apimachinery.pkg.runtime.RawExtension" => {
                    return "FieldType::JsonRaw".to_string()
                }
                ".k8s.io.apimachinery.pkg.api.resource.Quantity" => {
                    return "FieldType::String".to_string()
                }
                _ => {}
            }
            // Go `,inline` embeds surface as these named message fields; K8s
            // JSON flattens them into the parent object.
            if matches!(json, "volumeSource" | "persistentVolumeSource" | "localObjectReference") {
                return format!("FieldType::Inlined({short:?}.to_string())");
            }
            format!("FieldType::Message({short:?}.to_string())")
        }
    }
}
